IF (CASOCK_LIBRARY_PRO_ASIOBASE AND
    CASOCK_LIBRARY_PRO_ASIOCLIENT AND
    CASOCK_LIBRARY_PRO_ASIOSERVER AND
    CASOCK_LIBRARY_RPC_PB_BASE AND
    CASOCK_LIBRARY_RPC_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_PB_SERVER AND
    CASOCK_LIBRARY_RPC_SIO_PB_BASE AND
    CASOCK_LIBRARY_RPC_SIO_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_SIO_PB_SERVER AND
    CASOCK_LIBRARY_RPC_AIO_PB_BASE AND
    CASOCK_LIBRARY_RPC_AIO_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_AIO_PB_SERVER AND
    CASOCK_LIBRARY_SIOBASE AND
    CASOCK_LIBRARY_SIOCLIENT AND
    CASOCK_LIBRARY_SIOSERVER AND
    CASOCK_LIBRARY_UTIL AND
    CASOCK_INCLUDE_DIR)
  # in cache already
  SET(CASOCK_FOUND TRUE)
ELSE (CASOCK_LIBRARY_PRO_ASIOBASE AND
    CASOCK_LIBRARY_PRO_ASIOCLIENT AND
    CASOCK_LIBRARY_PRO_ASIOSERVER AND
    CASOCK_LIBRARY_RPC_PB_BASE AND
    CASOCK_LIBRARY_RPC_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_PB_SERVER AND
    CASOCK_LIBRARY_RPC_SIO_PB_BASE AND
    CASOCK_LIBRARY_RPC_SIO_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_SIO_PB_SERVER AND
    CASOCK_LIBRARY_RPC_AIO_PB_BASE AND
    CASOCK_LIBRARY_RPC_AIO_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_AIO_PB_SERVER AND
    CASOCK_LIBRARY_SIOBASE AND
    CASOCK_LIBRARY_SIOCLIENT AND
    CASOCK_LIBRARY_SIOSERVER AND
    CASOCK_LIBRARY_UTIL AND
    CASOCK_INCLUDE_DIR)

  SET(LIB_PATHS ${GNUWIN32_DIR}/lib)

  FIND_PATH(CASOCK_INCLUDE_DIR casock/base/CASException.h
    /usr/include
    /usr/local/include
  )

  FIND_LIBRARY(CASOCK_LIBRARY_PRO_ASIOBASE NAMES casproasiobase PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_PRO_ASIOCLIENT NAMES casproasioclient PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_PRO_ASIOSERVER NAMES casproasioserver PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_SIO_PB_BASE NAMES casrpcsiopbbase PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_SIO_PB_CLIENT NAMES casrpcsiopbclient PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_SIO_PB_SERVER NAMES casrpcsiopbserver PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_AIO_PB_BASE NAMES casrpcaiopbbase PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_AIO_PB_CLIENT NAMES casrpcaiopbclient PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_AIO_PB_SERVER NAMES casrpcaiopbserver PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_PB_BASE NAMES casrpcpbbase PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_PB_CLIENT NAMES casrpcpbclient PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_RPC_PB_SERVER NAMES casrpcpbserver PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_SIOBASE NAMES cassiobase PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_SIOCLIENT NAMES cassioclient PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_SIOSERVER NAMES cassioserver PATHS ${LIB_PATHS})
  FIND_LIBRARY(CASOCK_LIBRARY_UTIL NAMES casutil PATHS ${LIB_PATHS})

  INCLUDE(FindPackageHandleStandardArgs)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(casock DEFAULT_MSG
                                    CASOCK_INCLUDE_DIR
                                    CASOCK_LIBRARY_PRO_ASIOBASE
                                    CASOCK_LIBRARY_PRO_ASIOCLIENT
                                    CASOCK_LIBRARY_PRO_ASIOSERVER
                                    CASOCK_LIBRARY_RPC_SIO_PB_BASE
                                    CASOCK_LIBRARY_RPC_SIO_PB_CLIENT
                                    CASOCK_LIBRARY_RPC_SIO_PB_SERVER
                                    CASOCK_LIBRARY_RPC_AIO_PB_BASE
                                    CASOCK_LIBRARY_RPC_AIO_PB_CLIENT
                                    CASOCK_LIBRARY_RPC_AIO_PB_SERVER
                                    CASOCK_LIBRARY_RPC_PB_BASE
                                    CASOCK_LIBRARY_RPC_PB_CLIENT
                                    CASOCK_LIBRARY_RPC_PB_SERVER
                                    CASOCK_LIBRARY_SIOBASE
                                    CASOCK_LIBRARY_SIOCLIENT
                                    CASOCK_LIBRARY_SIOSERVER
                                    CASOCK_LIBRARY_UTIL)

  # ensure that they are cached
  SET(CASOCK_INCLUDE_DIR ${CASOCK_INCLUDE_DIR} CACHE INTERNAL "The casock include path")
  SET(CASOCK_LIBRARY_PRO_ASIOBASE ${CASOCK_LIBRARY_PRO_ASIOBASE} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_PRO_ASIOCLIENT ${CASOCK_LIBRARY_PRO_ASIOCLIENT} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_PRO_ASIOSERVER ${CASOCK_LIBRARY_PRO_ASIOSERVER} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_SIO_PB_BASE ${CASOCK_LIBRARY_RPC_SIO_PB_BASE} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_SIO_PB_CLIENT ${CASOCK_LIBRARY_RPC_SIO_PB_CLIENT} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_SIO_PB_SERVER ${CASOCK_LIBRARY_RPC_SIO_PB_SERVER} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_AIO_PB_BASE ${CASOCK_LIBRARY_RPC_AIO_PB_BASE} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_AIO_PB_CLIENT ${CASOCK_LIBRARY_RPC_AIO_PB_CLIENT} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_AIO_PB_SERVER ${CASOCK_LIBRARY_RPC_AIO_PB_SERVER} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_PB_BASE ${CASOCK_LIBRARY_RPC_PB_BASE} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_PB_CLIENT ${CASOCK_LIBRARY_RPC_PB_CLIENT} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_RPC_PB_SERVER ${CASOCK_LIBRARY_RPC_PB_SERVER} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_SIOBASE ${CASOCK_LIBRARY_SIOBASE} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_SIOCLIENT ${CASOCK_LIBRARY_SIOCLIENT} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_SIOSERVER ${CASOCK_LIBRARY_SIOSERVER} CACHE INTERNAL "The libraries needed to use casock library")
  SET(CASOCK_LIBRARY_UTIL ${CASOCK_LIBRARY_UTIL} CACHE INTERNAL "The libraries needed to use casock library")

ENDIF (CASOCK_LIBRARY_PRO_ASIOBASE AND
    CASOCK_LIBRARY_PRO_ASIOCLIENT AND
    CASOCK_LIBRARY_PRO_ASIOSERVER AND
    CASOCK_LIBRARY_RPC_PB_BASE AND
    CASOCK_LIBRARY_RPC_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_PB_SERVER AND
    CASOCK_LIBRARY_RPC_SIO_PB_BASE AND
    CASOCK_LIBRARY_RPC_SIO_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_SIO_PB_SERVER AND
    CASOCK_LIBRARY_RPC_AIO_PB_BASE AND
    CASOCK_LIBRARY_RPC_AIO_PB_CLIENT AND
    CASOCK_LIBRARY_RPC_AIO_PB_SERVER AND
    CASOCK_LIBRARY_SIOBASE AND
    CASOCK_LIBRARY_SIOCLIENT AND
    CASOCK_LIBRARY_SIOSERVER AND
    CASOCK_LIBRARY_UTIL AND
    CASOCK_INCLUDE_DIR)
