// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: btrfs_backend_service.proto

#ifndef PROTOBUF_btrfs_5fbackend_5fservice_2eproto__INCLUDED
#define PROTOBUF_btrfs_5fbackend_5fservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/service.h>
// @@protoc_insertion_point(includes)

namespace backend {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_btrfs_5fbackend_5fservice_2eproto();
void protobuf_AssignDesc_btrfs_5fbackend_5fservice_2eproto();
void protobuf_ShutdownFile_btrfs_5fbackend_5fservice_2eproto();

class EmptyMessage;

// ===================================================================

class EmptyMessage : public ::google::protobuf::Message {
 public:
  EmptyMessage();
  virtual ~EmptyMessage();
  
  EmptyMessage(const EmptyMessage& from);
  
  inline EmptyMessage& operator=(const EmptyMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const EmptyMessage& default_instance();
  
  void Swap(EmptyMessage* other);
  
  // implements Message ----------------------------------------------
  
  EmptyMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EmptyMessage& from);
  void MergeFrom(const EmptyMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:backend.EmptyMessage)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_btrfs_5fbackend_5fservice_2eproto();
  friend void protobuf_AssignDesc_btrfs_5fbackend_5fservice_2eproto();
  friend void protobuf_ShutdownFile_btrfs_5fbackend_5fservice_2eproto();
  
  void InitAsDefaultInstance();
  static EmptyMessage* default_instance_;
};
// ===================================================================

class BtrfsBackendService_Stub;

class BtrfsBackendService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline BtrfsBackendService() {};
 public:
  virtual ~BtrfsBackendService();
  
  typedef BtrfsBackendService_Stub Stub;
  
  static const ::google::protobuf::ServiceDescriptor* descriptor();
  
  virtual void Ping(::google::protobuf::RpcController* controller,
                       const ::backend::EmptyMessage* request,
                       ::backend::EmptyMessage* response,
                       ::google::protobuf::Closure* done);
  
  // implements Service ----------------------------------------------
  
  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(BtrfsBackendService);
};

class BtrfsBackendService_Stub : public BtrfsBackendService {
 public:
  BtrfsBackendService_Stub(::google::protobuf::RpcChannel* channel);
  BtrfsBackendService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~BtrfsBackendService_Stub();
  
  inline ::google::protobuf::RpcChannel* channel() { return channel_; }
  
  // implements BtrfsBackendService ------------------------------------------
  
  void Ping(::google::protobuf::RpcController* controller,
                       const ::backend::EmptyMessage* request,
                       ::backend::EmptyMessage* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(BtrfsBackendService_Stub);
};


// ===================================================================


// ===================================================================

// EmptyMessage


// @@protoc_insertion_point(namespace_scope)

}  // namespace backend

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_btrfs_5fbackend_5fservice_2eproto__INCLUDED
